# Generated by Django 5.1.1 on 2024-09-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_availability_mentor_alter_booking_mentor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
