# Generated by Django 5.0 on 2024-06-24 12:09

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='introductory_video',
            field=models.URLField(blank=True, null=True, validators=[events.models.validate_youtube_url]),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='takeaways',
            field=models.TextField(blank=True, null=True),
        ),
    ]
