# Generated by Django 5.0 on 2024-06-18 19:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='introductory_video',
            field=models.URLField(blank=True, null=True, validators=[core.models.validate_youtube_url]),
        ),
    ]
