# Generated by Django 5.0 on 2024-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mentor_introductory_video'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='schedule',
        ),
        migrations.AddField(
            model_name='mentor',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='scheduling.availability'),
        ),
    ]
