# Generated by Django 5.0 on 2024-06-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mentor_schedule_mentor_schedule'),
        ('industry', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='toolkits_used',
        ),
        migrations.AddField(
            model_name='mentor',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='industry.expertise'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='toolkits_used',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='tools.tool'),
        ),
    ]
