# Generated by Django 5.0 on 2024-06-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_mentor_expertise_remove_mentor_toolkits_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='content_links',
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='core.mentor')),
            ],
        ),
    ]
