# Generated by Django 5.0 on 2024-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mentor_content_links_contentlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlink',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='content_links',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='core.contentlink'),
        ),
    ]
