# Generated by Django 5.0 on 2024-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contentlink_mentor_mentor_content_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='content_links',
        ),
        migrations.DeleteModel(
            name='ContentLink',
        ),
        migrations.AddField(
            model_name='mentor',
            name='content_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
