# Generated by Django 5.0 on 2024-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_mentor'),
        ('core', '0007_remove_mentor_content_links_delete_contentlink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='content_links',
        ),
        migrations.AddField(
            model_name='mentor',
            name='content_links',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='articles.article'),
        ),
    ]
