# Generated by Django 5.0 on 2024-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_mentor'),
        ('core', '0008_remove_mentor_content_links_mentor_content_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='content_links',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.article'),
        ),
    ]
