# Generated by Django 5.0 on 2024-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mentor_content_links'),
        ('workex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='experience',
        ),
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='workex.workexperience'),
        ),
    ]
