# Generated by Django 5.0 on 2024-06-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_mentor_experience_mentor_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('15', '15 Minutes'), ('30', '30 Minutes'), ('60', '1 Hour')], max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='time_blocks',
        ),
        migrations.AddField(
            model_name='mentor',
            name='time_blocks',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='core.timeblock'),
        ),
    ]
