# Generated by Django 5.0 on 2024-06-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workexperience_alter_mentor_experience'),
        ('workex', '0002_workexperience_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='workex.workexperience'),
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
