# Generated by Django 5.0 on 2024-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeBlock',
        ),
        
    ]
