# Generated by Django 5.1.1 on 2024-09-24 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mentor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
