# Generated by Django 5.1.1 on 2024-09-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mentor_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='schedule',
        ),
        migrations.CreateModel(
            name='MentorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_appointments', to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration', models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_time_slots', to='core.mentor')),
            ],
            options={
                'unique_together': {('mentor', 'slot_duration')},
            },
        ),
        migrations.DeleteModel(
            name='MentorTimeBlock',
        ),
    ]
