# Generated by Django 5.1.1 on 2024-09-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_mentor_schedule_mentorappointment_and_more'),
        ('scheduling', '0010_alter_availability_mentor_alter_booking_mentor_and_more'),
        ('time_blocks', '0003_remove_timeblock_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentortimeslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mentortimeslot',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='scheduling.availability'),
        ),
        migrations.CreateModel(
            name='MentorTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_time_blocks', to='core.mentor')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_time_blocks', to='time_blocks.timeblock')),
            ],
            options={
                'unique_together': {('mentor', 'time_block')},
            },
        ),
        migrations.DeleteModel(
            name='MentorAppointment',
        ),
        migrations.DeleteModel(
            name='MentorTimeSlot',
        ),
    ]
