# Generated by Django 5.1.1 on 2024-09-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_mentortimeslot_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_availabilities', to='core.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='availabilities',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='core.availability'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_time_slots', to='core.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='time_slots',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='core.timeslot'),
        ),
    ]
