# Generated by Django 5.1.1 on 2024-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_booking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='schedule',
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
