# Generated by Django 5.1.1 on 2024-10-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_mentor_schedule_booking_meeting_link'),
        ('scheduling', '0015_availability_timeslot_delete_googlecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='scheduling.availability'),
        ),
    ]
