# Generated by Django 5.1.1 on 2024-10-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
