# Generated by Django 5.0 on 2024-06-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mentor_experience_delete_workexperience'),
        ('workex', '0002_workexperience_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='core.mentor'),
        ),
    ]
