# Generated by Django 5.1.1 on 2024-09-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0003_category_companylogo_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ceo_images/')),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_title',
            field=models.CharField(default='Built for founders, marketers, and product people.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cards',
            field=models.ManyToManyField(related_name='homepage_cards', to='webadmin.cardsection'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ceo_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webadmin.ceo'),
        ),
    ]
