# Generated by Django 5.1.1 on 2024-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0004_cardsection_ceo_homepage_section_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get 1:1 Mentorship from Top Startup Experts', max_length=255)),
                ('subtitle', models.CharField(default="India's 1st Startup Mentorship Platform", max_length=255)),
                ('description', models.TextField(default='Don’t waste your time in Trial & Errors, Book 1:1 personalized session with Top experts in various industries.')),
                ('video_url', models.URLField(blank=True, help_text='YouTube URL for the video', null=True)),
                ('top_mentors_count', models.IntegerField(default=100)),
                ('happy_mentees_count', models.IntegerField(default=500)),
                ('sessions_done_count', models.IntegerField(default=1000)),
                ('rating_stars', models.FloatField(default=4.8)),
                ('rating_label', models.CharField(default='Rated by Users', max_length=255)),
            ],
        ),
    ]
