# Generated by Django 5.1.1 on 2024-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0005_mentoringcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenttalkCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='menttalk_images/')),
                ('button_text', models.CharField(max_length=255)),
                ('button_url', models.URLField()),
                ('price', models.CharField(max_length=50)),
                ('preorder_info', models.CharField(max_length=255)),
                ('availability_info', models.CharField(max_length=255)),
                ('extra_info', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
