# Generated by Django 5.1.1 on 2024-09-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0006_menttalkcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Expert Bells', max_length=255)),
                ('about_text', models.TextField()),
                ('hashtag', models.CharField(default='#GrowWithGuidance', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('copyright', models.CharField(default='© Copyright 2024 Expert Bells All Rights Reserved.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('section', models.CharField(choices=[('company', 'Company'), ('quick', 'Quick Links'), ('compliance', 'Compliance')], max_length=50)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='webadmin.footer')),
            ],
        ),
        migrations.AddField(
            model_name='footer',
            name='social_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webadmin.sociallinks'),
        ),
    ]
