# Generated by Django 5.1.1 on 2024-09-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0008_alter_footer_company_name_alter_footer_copyright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardOfAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='board_photos/')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CTAButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_members',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_us_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='intro_images/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sub_intro_image1',
            field=models.ImageField(blank=True, null=True, upload_to='intro_images/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sub_intro_image2',
            field=models.ImageField(blank=True, null=True, upload_to='intro_images/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='blogs',
            field=models.ManyToManyField(related_name='about_page_blogs', to='webadmin.blogcard'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='board_of_advisors',
            field=models.ManyToManyField(related_name='about_page_board', to='webadmin.boardofadvisor'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='core_values',
            field=models.ManyToManyField(related_name='about_page_core_values', to='webadmin.corevalue'),
        ),
        migrations.CreateModel(
            name='CTACard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('buttons', models.ManyToManyField(to='webadmin.ctabutton')),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webadmin.ctacard'),
        ),
    ]
