# Generated by Django 5.1.1 on 2024-09-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0009_blogcard_boardofadvisor_corevalue_ctabutton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
