# Generated by Django 5.1.1 on 2024-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0010_teammates'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='teammates',
            field=models.ManyToManyField(related_name='about_teammates', to='webadmin.teammates'),
        ),
    ]
