# Generated by Django 5.1.1 on 2024-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0011_aboutpage_teammates'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammates',
            name='linkedinurl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammates',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
