# Generated by Django 5.0 on 2024-08-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
