# Generated by Django 5.0 on 2024-08-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_blocks', '0002_timeblock_price_alter_timeblock_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='price',
        ),
    ]
