# Generated by Django 5.1.1 on 2024-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='expertise_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
