# Generated by Django 5.0 on 2024-08-11 07:51

import cohorts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_remove_customuser_otp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('takeaways', models.TextField()),
                ('introductory_video', models.URLField(blank=True, null=True, validators=[cohorts.models.validate_youtube_url])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='core.mentor')),
            ],
        ),
    ]
