# Generated by Django 5.0 on 2024-08-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_rename_payment_date_cohortregistration_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
