# Generated by Django 5.0 on 2024-08-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
