# Generated by Django 5.0 on 2024-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0010_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='d7dddab4-70ee-4004-ad8c-04e96fded3f3', max_length=100, unique=True),
        ),
    ]
