# Generated by Django 5.0 on 2024-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='150fc4b3-bf4f-4cb6-9582-06d2dfdb31ae', max_length=100, unique=True),
        ),
    ]
