# Generated by Django 5.0 on 2024-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0013_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='fc311f7c-6c4b-48d0-8fdb-fc0f4fd1eece', max_length=100, unique=True),
        ),
    ]
