# Generated by Django 5.0 on 2024-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0014_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='b48504dc-4fe2-4c0a-86c9-351cab522bfe', max_length=100, unique=True),
        ),
    ]
