# Generated by Django 5.0 on 2024-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0015_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='27d930c9-16da-4a02-b8a7-bce4425788e1', max_length=100, unique=True),
        ),
    ]
