# Generated by Django 5.0 on 2024-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0018_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='4ab6d49b-5a7f-446c-8ed9-e3dae4ffad47', max_length=100, unique=True),
        ),
    ]
