# Generated by Django 5.0 on 2024-08-29 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0021_alter_cohort_end_date_alter_cohort_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 8, 58, 8, 396340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 8, 58, 8, 396168, tzinfo=datetime.timezone.utc)),
        ),
    ]
